[package]
name = "ldclient"
version = "0.1.0"
authors = ["Eli Bishop <eli@launchdarkly.com>"]

[dependencies]
regex = "0.2"
reqwest = "0.8"
semver = "0.9"
serde_json = "1.0.9"
serde = "1.0"
serde_derive = "1.0"
sha1 = "0.6"
time = "0.1"
